packages/semver/jest.config.js, packages/semver/src/builders/version/builder.spec.ts, packages/semver/src/builders/version/builder.ts, packages/semver/src/builders/version/release.ts, packages/semver/src/builders/version/schema.d.ts, packages/semver/src/builders/version/schema.json
Close #1
I had some issues with the `standard-version` mock that was not restored after each tests, that's why I touched the jest.config and created a release.ts file. @yjaaidi if you know a sexier way to mock this here, let me know. I'm not a fan of `release.release` but I struggled a long time...
=> feat: ✅ autodetect first release, remove related option

packages/semver/src/builders/version/builder.e2e.spec.ts, packages/semver/src/builders/version/builder.ts, packages/semver/src/builders/version/schema.d.ts, packages/semver/src/builders/version/utils/try-bump.spec.ts, packages/semver/src/builders/version/utils/try-bump.ts
* `major`, `minor` and `patch` are able to be specified through command line
* prerelease identifiers are supported within this explicit bumping that follows the original semver design: https://github.com/npm/node-semver#prerelease-identifiers
This pull request closes #56
=> feat: ✅ bump version explicitly through parameters

README.md, packages/semver/migrations.json, packages/semver/package.json, packages/semver/src/builders/version/builder.e2e.spec.ts, packages/semver/src/builders/version/builder.spec.ts, packages/semver/src/builders/version/builder.ts, packages/semver/src/builders/version/schema.d.ts, packages/semver/src/builders/version/schema.json, packages/semver/src/builders/version/utils/git.spec.ts, packages/semver/src/builders/version/utils/git.ts, packages/semver/src/builders/version/version.ts, packages/semver/src/migrations/update-2-0-0/index.spec.ts, packages/semver/src/migrations/update-2-0-0/index.ts
Related to [this comment](https://github.com/jscutlery/semver/issues/135#issuecomment-815941240), add the ability to skip project changelog generation with sync mode. Also renamed --root-changelog option to --skip-root-changelog, which is more conventional.
We can also provide a migration script to automatically migrate to the new option.
=> Skip individual changelog

packages/semver/src/generators/install/utils/dependencies.ts
When trying to run `nx g @jscutlery/semver:install` the command fails in case that the `.husky` folder already exists.
Seems like updating the code to work with the `tree` solves the issue. ([nx pr 5695](https://github.com/nrwl/nx/pull/5695) was merged)
=> Install generator fails when .husky folder exists

packages/semver/src/executors/version/index.ts, packages/semver/src/executors/version/schema.json
By having default value of versionTagPrefix set to `undefined` we allow setting prefix to empty string `""`.
=> feat(semver): ✔️  use undefined as default value of versionTagPrefix

nx.json, packages/semver/project.json, workspace.json
Converts the default structure to the new standalone projects configuration.
closes: #320
=> fix: use standalone projects

.github/workflows/test-and-release.yml, .husky/commit-msg, commitlint.config.js, package.json, packages/semver/src/generators/install/index.spec.ts, packages/semver/src/generators/install/utils/dependencies.ts
- Configure commitlint in a dedicated  `.commitlintrc.js` file,
- extends `@commitlint/config-angular` rules
- update commitlint packages
- stick to `@commitlint/config-angular` types for semver linting
- run commitlint in the ci
=> Follow `@commitlint/config-angular`

.github/actions/setup/action.yml
I had the same action to set up my node dependencies as you; I noticed the cache seems not to be working on my workflows. In the face of installing the dependencies, it was taking a considerable amount of time, so I decided to investigate.
After reading the documentation of the action [actions/setup-node](https://github.com/actions/setup-node#readme), I found that they indicate a way to manage the cache, so I decided to try it.
**The result is positive 🟢**, an improvement of 32% on average (at least for lint, build, check commit message and, unit test). You can see all the analysis on the [PR](https://github.com/bikecoders/ngx-deploy-npm/pull/137) that I did for ngx-deploy-npm
---
You can notice the improvement right in this PR
=> ci: ⚙️ improve CI operations time by 32% in average

packages/semver/src/executors/version/testing.ts, packages/semver/src/executors/version/utils/post-target.spec.ts, packages/semver/src/executors/version/utils/post-target.ts
Fixes jscutlery/semver#372
Handle errors originating from `@nrwl/devkit` *read-target-options* when target project does not exist in workspace or when target name is not configured on project
Reuse same logic from *read-target-options* to retrieve project and targets to perform a check before using it
```js
function readTargetOptions({ project, target, configuration }, context) {
const projectConfiguration = context.workspace.projects[project];
const targetConfiguration = projectConfiguration.targets[target];
[...]
}
```
=> fix(semver): handle post target executor errors

packages/semver/src/executors/github/schema.json
The schema option is named `notesFiles` but docs & executor use `notesFile`
=> Fix | Typo on `notesFile`

packages/semver/src/executors/version/utils/get-last-version.spec.ts, packages/semver/src/executors/version/utils/get-last-version.ts, packages/semver/src/executors/version/utils/try-bump.spec.ts, packages/semver/src/executors/version/utils/try-bump.ts
This PR makes it possible to get the latest version not from the last tag, but from the last release tag, the problem we were having is that we release a lot of beta versions and when we tried to make a final release it wasn't possible to do it automatically because the last beta tag existed and it would not detect any changes after it.
=> feat(semver): filter out prerelease tags if trying to release

README.md, packages/semver/builders.json, packages/semver/src/executors/gitlab/README.md, packages/semver/src/executors/gitlab/compat.ts, packages/semver/src/executors/gitlab/executor.spec.ts, packages/semver/src/executors/gitlab/executor.ts, packages/semver/src/executors/gitlab/schema.d.ts, packages/semver/src/executors/gitlab/schema.json
Hi all,
This is a small PR which adds in a GitLab alternative to the GitHub release executor.
My company is using this package and we love it but we use GitLab for CI/CD so thought it'd be nice to get this functionality added into this extension.
This is a fairly quick draft so happy to receive help/pointers to get this merged.
Thanks!
=> feat(semver): add gitlab releases executor

.github/renovate.json
I see that your Depency Dashboard is presenting a warning.
It must be because you are using the deprecated option [`commitMessage`](https://github.com/jscutlery/semver/blob/main/.github/renovate.json#L14) on Renovate's config.
I already solve it on the ngx-deploy-npm repo. It took me several tries to figure out the proper config, but this is the first PR related to it, and its well-documented -> https://github.com/bikecoders/ngx-deploy-npm/pull/267
You can compare the [current configuration](https://github.com/bikecoders/ngx-deploy-npm/blob/master/renovate.json) on ngx-deploy-npm. You can check the PR's commits structure:
- https://github.com/bikecoders/ngx-deploy-npm/pull/268
- https://github.com/bikecoders/ngx-deploy-npm/pull/269
The warning disappeared from the [Dependency …
=> ci: update deprecated renovate option

packages/semver/src/executors/version/utils/git.ts, packages/semver/src/executors/version/version.ts
Fixed issue where staging changes in versionWorkspace() could occur in parallel could cause git to throw an error related to the lockfile.
Related to #507, #500
=> fix: version workspace now stages all changes together

packages/semver/src/executors/gitlab/executor.spec.ts, packages/semver/src/executors/gitlab/executor.ts
fixes the problem, that the gitlab-executor throws an "invalid delimiter" error when assets are defined
now we follow the same structure for assets, as we do for milestones in the "release-cli" arguments
```
console.log
[
'create',
'--tag-name',
'1.2.3',
'--description',
'# My Notes',
`--assets-link='{"name": "first", "url": "asset"}'`,
`--assets-link='{"name": "second", "url": "asset"}'`
]
at src/executors/gitlab/executor.ts:37:11
console.error
Error: time="2022-06-03T08:56:14+02:00" level=info msg="Creating Release..." cli=release-cli command=create name= project-id=12345 ref= server-url="https://...net" tag-name=1.2.3 version=0.11.0
time="2022-06-03T08:56:14+02:00" level=fatal msg="run app" cli=release-cli error="new CreateReleaseRequest: failed to parse assets: 2 errors occurred:\n\t* …
```
=> fix(semver): invalid delimiter for asset

packages/semver/src/executors/version/utils/post-target.spec.ts, packages/semver/src/executors/version/utils/post-target.ts
fixes a problem with the introduced recursive replacement of template-strings, where arrays of primitive datatypes were handled like an object.
=> fix(semver): fix handling of non-object arrays in options

packages/semver/src/executors/version/utils/git.spec.ts, packages/semver/src/executors/version/utils/git.ts
Hello everyone,
This fixes #593. It does not use any heuristics to select the commit, simply picks the last one returned by `git rev-list --max-parents=0 HEAD`
🎈
=> fix(semver): deal with unrelated histories (#593)

packages/semver/jest.config.ts
On `ts-jest` v29:
> Define ts-jest config under globals is now deprecated. Please define the config via transformer config instead.
Currently, on the unit test, there is a [warning](https://github.com/jscutlery/semver/actions/runs/3200656733/jobs/5227816719#step:4:91). 
## New behavior
I updated config `ts-jest` to v29, and the warning is [gone](https://github.com/jscutlery/semver/actions/runs/3202620106/jobs/5231776265#step:4:196). 
I made these changes on the ngx-deploy-npm repo 
See [PR 378](https://github.com/bikecoders/ngx-deploy-npm/pull/378)
=> test: update deprecated ts-jest configuration

packages/semver/src/executors/version/index.ts
=> fix: version tagPrefix for dependencies not propagated

README.md
This PR will add a compatibility overview to the NX-dependency.
I started to add the overview however for some older versions I'm not completely clear.
I digged through the git history and collected this: 
V1.0.0
"@nrwl/cli": "11.0.1",
"@nrwl/nx-plugin": "^11.0.0",
"@nrwl/tao": "11.0.1",
"@nrwl/workspace": "11.0.1",
2.0.0
"@nrwl/cli": "11.6.2",
"@nrwl/nx-plugin": "11.6.2",
"@nrwl/tao": "11.6.2",
"@nrwl/workspace": "11.6.2",
2.4.0
"@nrwl/cli": "12.5.2",
"@nrwl/nx-plugin": "12.5.2",
"@nrwl/tao": "12.5.2",
"@nrwl/workspace": "12.5.2",
2.12.0
"@nrwl/cli": "13.1.3",
"@nrwl/nx-plugin": "13.1.3",
"@nrwl/tao": "13.1.3",
"@nrwl/workspace": "13.1.3",
means with the mentioned versions some Nx dependencies got bumped.
I'm not sure which of these Nx dependencies where required to run `semver`. 
Do you …
=> docs(semver): add nx compatibility overview

README.md, packages/semver/src/executors/version/index.ts, packages/semver/src/executors/version/schema.d.ts, packages/semver/src/executors/version/schema.json, packages/semver/src/executors/version/utils/try-bump.spec.ts, packages/semver/src/executors/version/utils/try-bump.ts
Previously it was impossible to use anything but
conventional commits because the header pattern could not be modified from the outside. Now you can provide you custom config through the option `commitParserOptions`. This is intended for use cases where ticket numbers are prefixing the conventional commit message.
=> feat: add possibility to provide a commit parser config

packages/semver/src/generators/install/__files/CHANGELOG.md, packages/semver/src/generators/install/index.spec.ts, packages/semver/src/generators/install/utils/create-changelog.ts, packages/semver/src/generators/install/utils/workspace.ts
This will close #711 
When `jscutlery/semver` is added to a project it will now create a `CHANGELOG.md` file.
~~Please note that I will still need to clean up this PR a bit (e.g. I did for now introduce some duplication in the spec-file). But of course feel free to already give feedback.~~
PR is now ready.
=> feat: create CHANGELOG.md when setting up semver for a project

README.md
Since the `postTargets` option uses `runExecutor` [under the hood](https://github.com/jscutlery/semver/blob/main/packages/semver/src/executors/version/utils/post-target.ts#L38), it would be nice to indicate the expected behavior to the users. `runExecutor` is not the same as running the target on the Nx CLI; it calls the target as it, without running any dependency or taking Nx Cache into account.
That behavior is not documented, but [according to the Nx Team](https://github.com/nrwl/nx/issues/19531#issuecomment-1760343458) that's the expected behavior.
> runExecutor runs a specific executor. It doesn't spawn the task orchestrator or any of that, so dependencies are not ran and caching is not considered.
=> docs: improve postTargets option behavior documentation

packages/semver/src/generators/install/index.spec.ts, packages/semver/src/generators/install/utils/dependencies.ts
Reference: https://github.com/typicode/husky/releases/tag/v9.0.1
=> fix(semver): migrate husky to v9 in npm prepare script

packages/semver/src/executors/version/utils/conventional-commit.ts
Passing the project root of the Nx project (a directory) always fails, as the code in `conventional-changelog` is [expecting a file path](https://github.com/conventional-changelog/conventional-changelog/blob/conventional-changelog-v5.1.0/packages/conventional-changelog-core/lib/merge-config.js#L114). So we need to explicitly pass the package.json path.
=> fix: pass package.json path through to `conventional-changelog`

README.md, packages/semver/src/executors/version/index.ts, packages/semver/src/executors/version/schema.d.ts, packages/semver/src/executors/version/schema.json, packages/semver/src/executors/version/utils/git.spec.ts, packages/semver/src/executors/version/utils/git.ts, packages/semver/src/executors/version/version.ts
With this option I can run my 241 libraries in parallel - which greatly improves the time it takes to version the libs - when running nx affected targets=version --parallel 8
Without this change it is not possible to run in parallel at all, as add to stage requires a git-lock
=> feat: added option to skip stage

packages/semver/src/executors/version/utils/git.spec.ts, packages/semver/src/executors/version/utils/git.ts
After adding addToStage skip support - I found that the chain is stopped and not continued - I managed to test it on my repo this time, and it works.
=> fix: support continue chain so package.json will be updated

README.md, packages/semver/package.json, yarn.lock
This PR updates the `peerDependencies` of the `@nx/devkit` package to include support for Nx version 21 (`^21.0.0`). This is a follow-up to the previously added support for Nx 20 and ensures compatibility with the latest Nx releases.
While upgrading to Nx 21, I noticed that the `@nx/devkit` peer dependency was still limited to version 20. This PR mirrors the approach taken in [#915](https://github.com/jscutlery/semver/pull/915), where support for Nx 20 was added via an identical change to the peer dependency range.
I followed the same approach as in the linked PR, but I was unsure how to verify that this change works correctly with Nx 21. I currently don't know the appropriate way to test whether the plugin still behaves as expected with the new version.
If there is a documented or …
=> feat: add support for Nx 21 in peerDependencies
